config/routes.rb
Rails.application.routes.draw do
  resources :categories do
    resource :comments
  end
  resources :posts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :category
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @category = Category.all
  end

  def show
    @category = Category.find(params[:id])
  end

  def new
    @category = Category.new
  end

  def edit
    @category = Category.find(params[:id])
  end

  def create
    @category = Category.new(category_params)
    @category.save
    redirect_to @category
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      redirect_to @category
    else
      render 'edit'
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    redirect_to categories_path
  end

  private
  def category_params
    params.require(:category).permit(:title, :text)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @category = Category.find(params[:category_id])
    @comment = @category.comments.create(comment_params)
    redirect_to category_path(@category)
  end

  private
  def comment_params
    params.require(:comment).permit(:title, :text)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @post = Post.all
  end

  def show
  end

  def new
    # @category = Category.find(params[:category_id])
    # @post = @category.posts.new(post_params)
  end

  def edit
    # @category = Category.find(params[:category_id])
    # @post = @category.posts
  end

  def create
    @category = Category.find(params[:category_id])
    @post = Post.new(post_params)
    @post.save
    redirect_to @post
  end

  def update
    @category = Category.find(params[:category_id])
    @post = @category.posts.update(post_params)
    if @post.update(post_params)
      redirect_to @category
    else
      render 'edit'
    end
  end

  private
  def post_params
    params.require(:post).permit(:title, :text, :category_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/categories/_form.html.erb
<%= form_for :category, url: categories_path do |f| %>

    <p>
      Название<br>
      <%= f.text_field(:title, {:class => 'form-control'}) %>
    </p>
    <p>
      Описание статьи<br>
      <%= f.text_area(:text,{:class => 'form-control'})%>
    </p>
    <p>

      <%= f.submit({:class => 'btn btn-info'}) %>
    </p>
<% end %>

app/views/categories/edit.html.erb
<h1>Редактирование категории</h1>

<%= render 'form' %>

<%= link_to "Назад", categories_path, :class => 'btn btn-info' %>

app/views/categories/index.html.erb
<h1>Все наши категории</h1>
  <% @category.each do |category| %>
    <div class="alert alert-light">
      <h2>Название категории:</h2>
  <h3><%= category.title %></h3>
      <h3>Описание категории:</h3>
    <p3><%= category.text %></p3>
      </p>
      <%= link_to "Показать категорию", category_path(category), class: 'btn btn-info' %>
      <%= link_to "Pедактировать", edit_category_path(category), class: 'btn btn-info' %>
      <%= link_to "Удалить", category_path(category), method: :delete, data: {confirm: "Хотите удалить категорию?"}, class: 'btn btn-danger' %>
      </p>
    </div>
    <br>
<% end %>

app/views/categories/new.html.erb
<h1>Добавление новой категории</h1>

<%= render 'form' %>

<%= link_to "Назад", categories_path, :class => 'btn btn-info' %>

app/views/categories/show.html.erb
<h1> <%= @category.title %></h1>
<p1> <%= @category.text %></p1>
<hr>
<h1>Все наши комментарии</h1>
<% @category.comments.each do |comment| %>
    <div class="alert alert-light">
      <h3><%= comment.title %></h3>
      <p3><%= comment.text %></p3>
    </div>
    <br>
<% end %>

<h2>Комментарии:</h2>
<%= form_for ( [@category, @category.comments.build] ) do |f| %>

    <p>
      Название<br>
      <%= f.text_field(:title, {:class => 'form-control'}) %>
    </p>
    <p>
      Текст комментария<br>
      <%= f.text_area(:text,{:class => 'form-control'})%>
    </p>
    <p>

      <%= f.submit("Добавить комментарий", {:class => 'btn btn-info'}) %>
      <%= link_to "Назад", categories_path, :class => 'btn btn-info' %>

    </p>

<% end %>

<h1>Создание нового поста</h1>
<% @category.posts.each do |post| %>
    <div class="alert alert-light">
      <h3><%= post.title %></h3>
      <p3><%= post.text %></p3>
    </div>
    <br>

<% end %>

<%= form_for :post, url: posts_path(@category) do |f| %>

    <p>
      Название поста<br>
      <%= f.text_field(:title, {:class => 'form-control'}) %>
    </p>
    <p>
      Описание поста<br>
      <%= f.text_area(:text,{:class => 'form-control'})%>
    </p>
    <p>

      <%= f.submit({:class => 'btn btn-info'}) %>
    </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <div>
  <body>
  <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
    <h5 class="my-0 mr-md-auto font-weight-Bold">Blog</h5>
    <nav class="my-2 my-md-0 mr-md-3">
      <span class="p-2 text-dark"><%= link_to "Главная страница",categories_path %></span>
    </nav>
    <span class="btn btn-outline"><%= link_to "Добавление категории", new_category_path %></span>
  </div>

  <div class="container">
    <%= yield %>
  </div>
  </body>
  </div>
</html>

app/views/posts/edit.html.erb
<h1>Редактирование поста</h1>
<%= form_for :post, url: posts_path do |f| %>
    <p>
      Название<br>
      <%= f.text_field(:title, {:class => 'form-control'}) %>
    </p>
    <p>
      Описание статьи<br>
      <%= f.text_area(:text,{:class => 'form-control'})%>
    </p>
    <p>

      <%= f.submit({:class => 'btn btn-info'}) %>
    </p>
    <p>
      <%= select("post", "category_id", Category.all.collect {|p| [ p.title, p.id ] }, { include_blank: true })  %>
    </p>

<% end %>

app/views/posts/index.html.erb
<h1>Все наши посты</h1>
<% @post.each do |post| %>
    <div class="alert alert-light">
      <h2>Название категории:</h2>
      <h3><%= post.title %></h3>
      <h3>Описание категории:</h3>
      <p3><%= post.text %></p3>
      </p>
      <%= link_to "Показать пост", category_path(post), class: 'btn btn-info' %>
      <%= link_to "Pедактировать", edit_post_path(post), class: 'btn btn-info' %>
      <%= link_to "Удалить", category_path(post), method: :delete, data: {confirm: "Хотите удалить категорию?"}, class: 'btn btn-danger' %>
      </p>
    </div>
    <br>
<% end %>

app/views/posts/new.html.erb
<h1>Добавление нового поста</h1>
<%= form_for :post, url: posts_path do |f| %>

    <p>
      Название поста<br>
      <%= f.text_field(:title, {:class => 'form-control'}) %>
    </p>
    <p>
      Описание поста<br>
      <%= f.text_area(:text,{:class => 'form-control'})%>
    </p>
    <p>
      <%= f.submit("Сохранить пост",{:class => 'btn btn-info'}) %>
      <%= link_to "Назад", categories_path, :class => 'btn btn-info' %>
    </p>

<% end %>